package:
    name: pyaqsapi
    version: 1.0.1

source:
    path: .\dist\pyaqsapi-1.0.1.tar.bz2
    sha256: ee37659075a5eaa25432464fe34ee3a00a2d906db9dbc85bcdd84e7178a7313c

build:
    noarch: python
    number: 0
    script: PYTHON setup.py install

run:
    - python

requirements:
  build:
    - python [py>=39]
    - setuptools
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-apidoc
    - sphinxcontrib-bibtex
    - toml
    - pep517
    - conda-build

  host:
    - python [py>=39]
    - wheel
    - pip
    - setuptools
    - tox-conda

  run:
    - python [py>=39]
    - keyring
    - pandas
    - requests
    - wheel
    - pip
    - certifi
    - cryptography
    - numpydoc

  pip:
    - datetime

test:
  imports:
    - pyaqsapi
  commands:
    - pip check
  requires:
    - python
    - pytest
    - pytest-rerunfailures
    - pytest-black
    - tox

about:
    home: https://github.com/USEPA/pyaqsapi
    license: MIT
    license_family: MIT
    license_file: LICENSE.rst
    summary: Retrieve Ambient Air Monitoring data from US EPA AQS DataMart
    description: Retrieve air monitoring data and associated metadata from the US Environmental Protection Agencys Air Quality System (AQS) DataMart API service using python functions.

extra:
  recipe-maintainers:
    - MCCROWEYCLINTON-EPA