"""Vulture whitelist configuration for pyaqsapi. This file should not be used for any other purpose."""

_.get_request_time  # unused method (pyaqsapi\helperfunctions.py:96)
_.get_numberofrows  # unused method (pyaqsapi\helperfunctions.py:107)
_.get_header  # unused method (pyaqsapi\helperfunctions.py:148)
_.get_status_code  # unused method (pyaqsapi\helperfunctions.py:159)
_.get_url  # unused method (pyaqsapi\helperfunctions.py:170)
_.get_status  # unused method (pyaqsapi\helperfunctions.py:181)
aqs_credentials  # unused function (pyaqsapi\helperfunctions.py:1183)
aqs_counties_by_state  # unused function (pyaqsapi\listfunctions.py:9)
aqs_sites_by_county  # unused function (pyaqsapi\listfunctions.py:45)
aqs_classes  # unused function (pyaqsapi\listfunctions.py:85)
aqs_parameters_by_class  # unused function (pyaqsapi\listfunctions.py:118)
aqs_mas  # unused function (pyaqsapi\listfunctions.py:159)
aqs_pqaos  # unused function (pyaqsapi\listfunctions.py:190)
aqs_cbsas  # unused function (pyaqsapi\listfunctions.py:220)
aqs_states  # unused function (pyaqsapi\listfunctions.py:251)
aqs_fields_by_service  # unused function (pyaqsapi\listfunctions.py:281)
aqs_sampledurations  # unused function (pyaqsapi\listfunctions.py:315)
aqs_is_available  # unused function (pyaqsapi\metadatafunctions.py:9)
aqs_knownissues  # unused function (pyaqsapi\metadatafunctions.py:35)
aqs_revisionhistory  # unused function (pyaqsapi\metadatafunctions.py:64)
aqs_sign_up  # unused function (pyaqsapi\setupfunctions.py:6)
