name: Bandit

on: [push, pull_request, workflow_dispatch]
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
        continue-on-error: true
        with:
          configfile: pyproject.toml
          targets: '.'
# jobs:
#   bandit_analyze:
#     runs-on: ubuntu-latest
#     permissions:
#       # required for all workflows
#       security-events: write
#       # only required for workflows in private repositories
#       actions: read
#       contents: read
#     steps:
#       # - name: Checkout code
#       #   uses: actions/checkout@v6
#       # - name: setup venv
#       #   run: apt-get update && apt install -y python3-venv
#       # - name: create venv
#       #   run: python3 -m venv ~/.python3/venv/pyaqsapi
#       # - name: install bandit using pip (ubuntu python3-bandit package does not read in toml files)
#       #   run: ~/.python3/venv/pyaqsapi/bin/pip install toml bandit[sarif]
#       # - name: run bandit
#       #   run: ~/.python3/venv/pyaqsapi/bin/python -m bandit -c pyproject.toml -r . 
#       - name: set up python
#         uses: actions/setup-python@v6
#         with:
#           python-version: '3.13' 
#       - name: Checkout code
#         uses: actions/checkout@v6
#       - name: Perform Bandit Analysis
#         uses: PyCQA/bandit-action@67a458d90fa11fb1463e91e7f4c8f068b5863c7f # v1.0.1
#         continue-on-error: true
#         with:
#           fetch-depth: 0
#           configfile: pyproject.toml
#           targets: '.'