name: Bandit

on: [push, pull_request, workflow_dispatch]

jobs:
  bandit_analyze:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
        with:
          configfile: "pyproject.toml"
          targets: "."
