name: new_build_and_test_pyaqsapi

on:
  push:
    branches:
      - main
      - github_workflow
  pull_request:
    branches:
      - main
      - github_workflow

jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      python-versions: '["3.10","3.11","3.12","3.13"]'
